### ISSUE TITLE
Error when executing cargo build

### ISSUE THREAD

**Issue by ErvinXie** [slint-ui/slint-rust-template#11]
error: current package believes it's in a workspace when it's not:
current:   /Users/ervinxie/Projects/slint/examples/gallery/my-project/Cargo.toml
workspace: /Users/ervinxie/Projects/slint/Cargo.toml

this may be fixable by adding `examples/gallery/my-project` to the `workspace.members` array of the manifest located at: /Users/ervinxie/Projects/slint/Cargo.toml
Alternatively, to keep it out of the workspace, add the package to the `workspace.exclude` array, or add an empty `[workspace]` table to the package's manifest.

**Comment by ogoffart** [comment]
Hi,

In the future, please use discussions to ask question ( https://github.com/slint-ui/slint/discussions )

This error happens because the `my-project` folder is within a sub-directory of `/Users/ervinxie/Projects/slint`  which itself  has a Cargo.toml

Workspaces are explained there: https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html

As the error message say, there are several way to fix this:
 1. Add `my-project`  to the `members` of the workspace in /Users/ervinxie/Projects/slint/Cargo.toml
 2. opt-out of the workspace, with the `exclude` or empty `workspace` in Cargo.toml
 3. move the folder somewhere else if it's not related
